// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 用户信息描述
 * @export
 * @interface ChameleonUser
 */
export interface ChameleonUser {
    /**
     * 用户 id
     * @type {string}
     * @memberof ChameleonUser
     */
    id: string;
    /**
     * 用户角色
     * @type {string}
     * @memberof ChameleonUser
     */
    role: string;
    /**
     * 用户昵称
     * @type {string}
     * @memberof ChameleonUser
     */
    nickname?: string;
    /**
     * 用户邮箱
     * @type {string}
     * @memberof ChameleonUser
     */
    email: string;
    /**
     * 用户状态
     * @type {string}
     * @memberof ChameleonUser
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ChameleonUser
     */
    lastLogin: string;
    /**
     * 
     * @type {string}
     * @memberof ChameleonUser
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof ChameleonUser
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof ChameleonUser
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof ChameleonUser
     */
    timezone?: string;
    /**
     * 
     * @type {string}
     * @memberof ChameleonUser
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ChameleonUser
     */
    mobile?: string;
    /**
     * 
     * @type {string}
     * @memberof ChameleonUser
     */
    avatar?: string;
}


