// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChameleonUserInfo
 */
export interface ChameleonUserInfo {
    /**
     * 
     * @type {string}
     * @memberof ChameleonUserInfo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ChameleonUserInfo
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ChameleonUserInfo
     */
    avatar?: string;
}


