// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ErrorsCode } from './errors-code';

/**
 * Err Code
 * @export
 * @interface Chameleonv1ErrCode
 */
export interface Chameleonv1ErrCode {
    /**
     * 状态码
     * @type {ErrorsCode}
     * @memberof Chameleonv1ErrCode
     */
    code: ErrorsCode;
    /**
     * 业务码
     * @type {number}
     * @memberof Chameleonv1ErrCode
     */
    bizCode: number;
    /**
     * 错误名字
     * @type {string}
     * @memberof Chameleonv1ErrCode
     */
    name: string;
    /**
     * 错误信息
     * @type {string}
     * @memberof Chameleonv1ErrCode
     */
    reason: string;
    /**
     * 错误详情
     * @type {Array<object>}
     * @memberof Chameleonv1ErrCode
     */
    details?: Array<object>;
}


