// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ErrorsCode } from './errors-code';

/**
 * 
 * @export
 * @interface ErrorsErrCode
 */
export interface ErrorsErrCode {
    /**
     * 
     * @type {ErrorsCode}
     * @memberof ErrorsErrCode
     */
    code?: ErrorsCode;
    /**
     * 
     * @type {number}
     * @memberof ErrorsErrCode
     */
    bizCode?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorsErrCode
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorsErrCode
     */
    reason?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof ErrorsErrCode
     */
    details?: Array<object>;
}


