// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */
export enum ErrorsCode {
    OK = 'OK',
    Canceled = 'Canceled',
    Unknown = 'Unknown',
    InvalidArgument = 'InvalidArgument',
    DeadlineExceeded = 'DeadlineExceeded',
    NotFound = 'NotFound',
    AlreadyExists = 'AlreadyExists',
    PermissionDenied = 'PermissionDenied',
    ResourceExhausted = 'ResourceExhausted',
    FailedPrecondition = 'FailedPrecondition',
    Aborted = 'Aborted',
    OutOfRange = 'OutOfRange',
    Unimplemented = 'Unimplemented',
    Internal = 'Internal',
    Unavailable = 'Unavailable',
    DataLoss = 'DataLoss',
    Unauthenticated = 'Unauthenticated',
    TooManyRequests = 'TooManyRequests'
}



