// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject8
 */
export interface InlineObject8 {
    /**
     * 密码
     * @type {string}
     * @memberof InlineObject8
     */
    password: string;
    /**
     * 老密码
     * @type {string}
     * @memberof InlineObject8
     */
    oldPassword: string;
    /**
     * 密码是否加密
     * @type {boolean}
     * @memberof InlineObject8
     */
    isEncrypted?: boolean;
}


