// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SearchPopularCitiesRspCity
 */
export interface SearchPopularCitiesRspCity {
    /**
     * 缩略图
     * @type {string}
     * @memberof SearchPopularCitiesRspCity
     */
    thumbnail?: string;
    /**
     * 城市名
     * @type {string}
     * @memberof SearchPopularCitiesRspCity
     */
    name?: string;
    /**
     * 房子数
     * @type {number}
     * @memberof SearchPopularCitiesRspCity
     */
    count?: number;
}


