// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Room } from './v1-room';
import { V1Story } from './v1-story';

/**
 * 
 * @export
 * @interface SharingResData
 */
export interface SharingResData {
    /**
     * 故事文档
     * @type {V1Story}
     * @memberof SharingResData
     */
    story?: V1Story;
    /**
     * 民宿房间
     * @type {V1Room}
     * @memberof SharingResData
     */
    room?: V1Room;
}


