// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents a time interval, encoded as a Timestamp start (inclusive) and a Timestamp end (exclusive).  The start must be less than or equal to the end. When the start equals the end, the interval is empty (matches no time). When both start and end are unspecified, the interval matches any time.
 * @export
 * @interface TypeInterval
 */
export interface TypeInterval {
    /**
     * Optional. Inclusive start of the interval.  If specified, a Timestamp matching this interval will have to be the same or after the start.
     * @type {string}
     * @memberof TypeInterval
     */
    startTime?: string;
    /**
     * Optional. Exclusive end of the interval.  If specified, a Timestamp matching this interval will have to be before the end.
     * @type {string}
     * @memberof TypeInterval
     */
    endTime?: string;
}


