// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdatePasswordReq
 */
export interface UpdatePasswordReq {
    /**
     * 认证 token
     * @type {string}
     * @memberof UpdatePasswordReq
     */
    token?: string;
    /**
     * 密码
     * @type {string}
     * @memberof UpdatePasswordReq
     */
    password?: string;
    /**
     * 老密码
     * @type {string}
     * @memberof UpdatePasswordReq
     */
    oldPassword?: string;
}


