// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface User1
 */
export interface User1 {
    /**
     * 
     * @type {number}
     * @memberof User1
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    timezone?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof User1
     */
    groups?: Array<string>;
}


