// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { User } from './user';
import { User1 } from './user1';

/**
 * 用户信息  任何一个都可以
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 
     * @type {User}
     * @memberof UserInfo
     */
    user1?: User;
    /**
     * 
     * @type {User1}
     * @memberof UserInfo
     */
    user2?: User1;
}


