// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1Attraction
 */
export interface V1Attraction {
    /**
     * 
     * @type {string}
     * @memberof V1Attraction
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof V1Attraction
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof V1Attraction
     */
    updatedAt: string;
    /**
     * 景点名字
     * @type {string}
     * @memberof V1Attraction
     */
    name: string;
    /**
     * 景点种类
     * @type {string}
     * @memberof V1Attraction
     */
    catalog?: string | null;
    /**
     * 景点所在国家
     * @type {string}
     * @memberof V1Attraction
     */
    country: string;
    /**
     * 景点所在城市
     * @type {string}
     * @memberof V1Attraction
     */
    city: string;
    /**
     * 景点详细地址
     * @type {string}
     * @memberof V1Attraction
     */
    address: string;
    /**
     * 景点纬度
     * @type {number}
     * @memberof V1Attraction
     */
    latitude: number;
    /**
     * 景点经度
     * @type {number}
     * @memberof V1Attraction
     */
    longitude: number;
    /**
     * 景点图片
     * @type {Array<string>}
     * @memberof V1Attraction
     */
    images?: Array<string>;
    /**
     * 景点介绍
     * @type {string}
     * @memberof V1Attraction
     */
    description?: string | null;
    /**
     * 附近的房间
     * @type {Array<string>}
     * @memberof V1Attraction
     */
    nearbyRooms?: Array<string>;
}


