// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1RoleName } from './v1-role-name';

/**
 * 
 * @export
 * @interface V1AuthLoginResponse
 */
export interface V1AuthLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof V1AuthLoginResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof V1AuthLoginResponse
     */
    jwtToken: string;
    /**
     * 
     * @type {string}
     * @memberof V1AuthLoginResponse
     */
    expired: string;
    /**
     * 
     * @type {V1RoleName}
     * @memberof V1AuthLoginResponse
     */
    role: V1RoleName;
}


