// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1AuthAuthorizeRsp
 */
export interface V1AuthAuthorizeRsp {
    /**
     * 第三方登录重定向地址
     * @type {string}
     * @memberof V1AuthAuthorizeRsp
     */
    redirectUri: string;
}


