// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1AuthLoginRequest
 */
export interface V1AuthLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof V1AuthLoginRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof V1AuthLoginRequest
     */
    password: string;
    /**
     * 密码是否加密
     * @type {boolean}
     * @memberof V1AuthLoginRequest
     */
    isEncrypted?: boolean;
}


