// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1ResKind } from './v1-res-kind';

/**
 * 
 * @export
 * @interface V1BookmarkFindReq
 */
export interface V1BookmarkFindReq {
    /**
     * 资源类型
     * @type {V1ResKind}
     * @memberof V1BookmarkFindReq
     */
    resKind?: V1ResKind;
    /**
     * 
     * @type {string}
     * @memberof V1BookmarkFindReq
     */
    sortBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof V1BookmarkFindReq
     */
    page?: number | null;
    /**
     * 
     * @type {number}
     * @memberof V1BookmarkFindReq
     */
    pageSize?: number | null;
}


