// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1BathingFacilities
 */
export interface V1BathingFacilities {
    /**
     * 浴缸
     * @type {boolean}
     * @memberof V1BathingFacilities
     */
    bathtub?: boolean;
    /**
     * 热水
     * @type {boolean}
     * @memberof V1BathingFacilities
     */
    hotWater?: boolean;
    /**
     * 浴霸
     * @type {boolean}
     * @memberof V1BathingFacilities
     */
    bathHeater?: boolean;
}


