// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1BalanceType } from './v1-balance-type';

/**
 * 
 * @export
 * @interface V1Balance
 */
export interface V1Balance {
    /**
     * 
     * @type {string}
     * @memberof V1Balance
     */
    id: string;
    /**
     * 创建日期
     * @type {string}
     * @memberof V1Balance
     */
    createdAt: string;
    /**
     * 修改日期
     * @type {string}
     * @memberof V1Balance
     */
    updatedAt: string;
    /**
     * 余额类型
     * @type {V1BalanceType}
     * @memberof V1Balance
     */
    type: V1BalanceType;
    /**
     * 余额
     * @type {string}
     * @memberof V1Balance
     */
    value: string;
    /**
     * 余额账户
     * @type {string}
     * @memberof V1Balance
     */
    userId: string;
}


