// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1ResKind } from './v1-res-kind';
import { V1UserInfo } from './v1-user-info';

/**
 * 收藏
 * @export
 * @interface V1Bookmark
 */
export interface V1Bookmark {
    /**
     * 
     * @type {string}
     * @memberof V1Bookmark
     */
    id: string;
    /**
     * 创建日期
     * @type {string}
     * @memberof V1Bookmark
     */
    createdAt: string;
    /**
     * 修改日期
     * @type {string}
     * @memberof V1Bookmark
     */
    updatedAt: string;
    /**
     * 用户信息
     * @type {V1UserInfo}
     * @memberof V1Bookmark
     */
    userInfo: V1UserInfo;
    /**
     * 资源类型
     * @type {V1ResKind}
     * @memberof V1Bookmark
     */
    resKind: V1ResKind;
    /**
     * 资源 id
     * @type {string}
     * @memberof V1Bookmark
     */
    resId: string;
    /**
     * 标题
     * @type {string}
     * @memberof V1Bookmark
     */
    title?: string | null;
    /**
     * 描述
     * @type {string}
     * @memberof V1Bookmark
     */
    description?: string | null;
    /**
     * 缩略图
     * @type {string}
     * @memberof V1Bookmark
     */
    thumbnail?: string | null;
}


