// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 地理位置
 * @export
 * @interface V1GeoLocation
 */
export interface V1GeoLocation {
    /**
     * 纬度
     * @type {number}
     * @memberof V1GeoLocation
     */
    latitude: number;
    /**
     * 经度
     * @type {number}
     * @memberof V1GeoLocation
     */
    longitude: number;
}


