// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1Group
 */
export interface V1Group {
    /**
     * 
     * @type {string}
     * @memberof V1Group
     */
    resType?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Group
     */
    groupType?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Group
     */
    groupId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V1Group
     */
    resources?: Array<string>;
    /**
     * 
     * @type {Array<V1Group>}
     * @memberof V1Group
     */
    children?: Array<V1Group>;
}


