// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1OrderDetail } from './v1-order-detail';
import { V1OrderStatus } from './v1-order-status';
import { V1Room } from './v1-room';
import { V1SpecialOrder } from './v1-special-order';

/**
 * 
 * @export
 * @interface V1Order
 */
export interface V1Order {
    /**
     * 
     * @type {string}
     * @memberof V1Order
     */
    id: string;
    /**
     * 创建日期
     * @type {string}
     * @memberof V1Order
     */
    createdAt: string;
    /**
     * 修改日期
     * @type {string}
     * @memberof V1Order
     */
    updatedAt: string;
    /**
     * 开始日期
     * @type {string}
     * @memberof V1Order
     */
    startDate: string;
    /**
     * 结束日期
     * @type {string}
     * @memberof V1Order
     */
    endDate: string;
    /**
     * 订单状态
     * @type {V1OrderStatus}
     * @memberof V1Order
     */
    status: V1OrderStatus;
    /**
     * 商品评论 id
     * @type {string}
     * @memberof V1Order
     */
    roomCommentId: string | null;
    /**
     * 商品 id
     * @type {string}
     * @memberof V1Order
     */
    roomId: string;
    /**
     * 用户 id
     * @type {string}
     * @memberof V1Order
     */
    userId: string;
    /**
     * 订单详情
     * @type {V1OrderDetail}
     * @memberof V1Order
     */
    detail?: V1OrderDetail;
    /**
     * 特殊服务订单
     * @type {Array<V1SpecialOrder>}
     * @memberof V1Order
     */
    specialOrders?: Array<V1SpecialOrder>;
    /**
     * 房间信息
     * @type {V1Room}
     * @memberof V1Order
     */
    room?: V1Room;
    /**
     * 可撤销截止时间
     * @type {string}
     * @memberof V1Order
     */
    cancellableTime?: string;
    /**
     * 分享 id
     * @type {string}
     * @memberof V1Order
     */
    shareId?: string | null;
    /**
     * 失败原因
     * @type {string}
     * @memberof V1Order
     */
    failedReason?: string | null;
}


