// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1OrderDetail
 */
export interface V1OrderDetail {
    /**
     * 成人数量
     * @type {number}
     * @memberof V1OrderDetail
     */
    adultsCount?: number;
    /**
     * 婴儿数量
     * @type {number}
     * @memberof V1OrderDetail
     */
    babyCount?: number;
    /**
     * 儿童数量
     * @type {number}
     * @memberof V1OrderDetail
     */
    childrenCount?: number;
    /**
     * 地方税和服务费
     * @type {number}
     * @memberof V1OrderDetail
     */
    serviceFee?: number;
    /**
     * 订单取消原因
     * @type {string}
     * @memberof V1OrderDetail
     */
    cancelReason?: string;
    /**
     * 顾客名字
     * @type {string}
     * @memberof V1OrderDetail
     */
    customerName?: string;
    /**
     * 顾客电话
     * @type {string}
     * @memberof V1OrderDetail
     */
    customerPhone?: string;
    /**
     * 总费用
     * @type {string}
     * @memberof V1OrderDetail
     */
    totalExpense?: string;
}


