// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1SpecialOrder } from './v1-special-order';

/**
 * 
 * @export
 * @interface V1OrderSpecialCreateReq
 */
export interface V1OrderSpecialCreateReq {
    /**
     * 
     * @type {V1SpecialOrder}
     * @memberof V1OrderSpecialCreateReq
     */
    order?: V1SpecialOrder;
}


