// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Order } from './v1-order';

/**
 * 
 * @export
 * @interface V1OrderCreateReq
 */
export interface V1OrderCreateReq {
    /**
     * 
     * @type {V1Order}
     * @memberof V1OrderCreateReq
     */
    order?: V1Order;
}


