// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Product } from './v1-product';

/**
 * 
 * @export
 * @interface V1ProductCreateReq
 */
export interface V1ProductCreateReq {
    /**
     * 
     * @type {V1Product}
     * @memberof V1ProductCreateReq
     */
    product?: V1Product;
}


