// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1Paging
 */
export interface V1Paging {
    /**
     * 
     * @type {number}
     * @memberof V1Paging
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof V1Paging
     */
    offset?: number;
}


