// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1ProductDetail } from './v1-product-detail';

/**
 * 
 * @export
 * @interface V1Product
 */
export interface V1Product {
    /**
     * 
     * @type {number}
     * @memberof V1Product
     */
    id?: number;
    /**
     * 创建日期
     * @type {string}
     * @memberof V1Product
     */
    createdAt?: string;
    /**
     * 修改日期
     * @type {string}
     * @memberof V1Product
     */
    updatedAt?: string;
    /**
     * 商品标题
     * @type {string}
     * @memberof V1Product
     */
    title?: string;
    /**
     * 商品数量
     * @type {number}
     * @memberof V1Product
     */
    count?: number;
    /**
     * 商品所在城市
     * @type {string}
     * @memberof V1Product
     */
    city?: string;
    /**
     * 商品详细地址
     * @type {string}
     * @memberof V1Product
     */
    address?: string;
    /**
     * 商品原价
     * @type {string}
     * @memberof V1Product
     */
    price?: string;
    /**
     * 折扣价格
     * @type {string}
     * @memberof V1Product
     */
    discountPrice?: string;
    /**
     * 商品介绍
     * @type {string}
     * @memberof V1Product
     */
    description?: string;
    /**
     * 
     * @type {V1ProductDetail}
     * @memberof V1Product
     */
    detail?: V1ProductDetail;
}


