// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Bookmarks } from './v1-bookmarks';
import { V1User } from './v1-user';
import { V1Users } from './v1-users';

/**
 * 
 * @export
 * @interface V1QueryResponse
 */
export interface V1QueryResponse {
    /**
     * 
     * @type {V1Bookmarks}
     * @memberof V1QueryResponse
     */
    bookmark?: V1Bookmarks;
    /**
     * 
     * @type {V1User}
     * @memberof V1QueryResponse
     */
    user?: V1User;
    /**
     * 
     * @type {V1Users}
     * @memberof V1QueryResponse
     */
    users?: V1Users;
}


