// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1QueryResponse } from './v1-query-response';

/**
 * 
 * @export
 * @interface V1QueryRsp
 */
export interface V1QueryRsp {
    /**
     * 
     * @type {Array<V1QueryResponse>}
     * @memberof V1QueryRsp
     */
    rsp?: Array<V1QueryResponse>;
}


