// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1QueryRequest } from './v1-query-request';

/**
 * 
 * @export
 * @interface V1QueryReq
 */
export interface V1QueryReq {
    /**
     * 
     * @type {Array<V1QueryRequest>}
     * @memberof V1QueryReq
     */
    req?: Array<V1QueryRequest>;
}


