// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1RoomInfo
 */
export interface V1RoomInfo {
    /**
     * 卧室数量
     * @type {number}
     * @memberof V1RoomInfo
     */
    rooms: number;
    /**
     * 床位数量
     * @type {number}
     * @memberof V1RoomInfo
     */
    beds: number;
    /**
     * 可容纳人数
     * @type {number}
     * @memberof V1RoomInfo
     */
    capacity: number;
    /**
     * 卫生间数量
     * @type {number}
     * @memberof V1RoomInfo
     */
    bathrooms: number;
}


