// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1BathingFacilities } from './v1-bathing-facilities';
import { V1RoomFreeService } from './v1-room-free-service';
import { V1RoomInfo } from './v1-room-info';
import { V1RoomInfrastructure } from './v1-room-infrastructure';
import { V1kitchenFacilities } from './v1kitchen-facilities';

/**
 * 
 * @export
 * @interface V1RoomDetail
 */
export interface V1RoomDetail {
    /**
     * 
     * @type {V1RoomInfo}
     * @memberof V1RoomDetail
     */
    info: V1RoomInfo;
    /**
     * 免费服务
     * @type {V1RoomFreeService}
     * @memberof V1RoomDetail
     */
    free?: V1RoomFreeService;
    /**
     * 基础设施
     * @type {V1RoomInfrastructure}
     * @memberof V1RoomDetail
     */
    infrastructure?: V1RoomInfrastructure;
    /**
     * 厨房设施
     * @type {V1kitchenFacilities}
     * @memberof V1RoomDetail
     */
    kitchen?: V1kitchenFacilities;
    /**
     * 洗浴设施
     * @type {V1BathingFacilities}
     * @memberof V1RoomDetail
     */
    bathing?: V1BathingFacilities;
    /**
     * 入住退房时间范围
     * @type {string}
     * @memberof V1RoomDetail
     */
    checkTime?: string;
    /**
     * 取消政策
     * @type {string}
     * @memberof V1RoomDetail
     */
    cancellationPolicy?: string;
    /**
     * 入住须知
     * @type {string}
     * @memberof V1RoomDetail
     */
    roomNotice?: string;
    /**
     * 服务费
     * @type {string}
     * @memberof V1RoomDetail
     */
    serviceFee?: string;
    /**
     * 地方税
     * @type {string}
     * @memberof V1RoomDetail
     */
    localTax?: string;
}


