// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1RoomAdditionalDetail } from './v1-room-additional-detail';
import { V1RoomAdditionalType } from './v1-room-additional-type';

/**
 * 房间特殊服务
 * @export
 * @interface V1RoomAdditional
 */
export interface V1RoomAdditional {
    /**
     * 
     * @type {string}
     * @memberof V1RoomAdditional
     */
    id: string;
    /**
     * 创建日期
     * @type {string}
     * @memberof V1RoomAdditional
     */
    createdAt: string;
    /**
     * 修改日期
     * @type {string}
     * @memberof V1RoomAdditional
     */
    updatedAt: string;
    /**
     * 服务名字
     * @type {string}
     * @memberof V1RoomAdditional
     */
    name: string;
    /**
     * 服务类型
     * @type {V1RoomAdditionalType}
     * @memberof V1RoomAdditional
     */
    type?: V1RoomAdditionalType;
    /**
     * 服务原价
     * @type {number}
     * @memberof V1RoomAdditional
     */
    price?: number;
    /**
     * 缩略图
     * @type {string}
     * @memberof V1RoomAdditional
     */
    thumbnail?: string;
    /**
     * 服务图片
     * @type {Array<string>}
     * @memberof V1RoomAdditional
     */
    images?: Array<string>;
    /**
     * 服务介绍
     * @type {string}
     * @memberof V1RoomAdditional
     */
    description?: string;
    /**
     * 
     * @type {V1RoomAdditionalDetail}
     * @memberof V1RoomAdditional
     */
    detail?: V1RoomAdditionalDetail;
}


