// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1SpecialService } from './v1-special-service';

/**
 * 
 * @export
 * @interface V1RoomCreateSpecialServiceReq
 */
export interface V1RoomCreateSpecialServiceReq {
    /**
     * 
     * @type {V1SpecialService}
     * @memberof V1RoomCreateSpecialServiceReq
     */
    specialService?: V1SpecialService;
}


