// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RoomFindBookableRspData } from './room-find-bookable-rsp-data';

/**
 * 
 * @export
 * @interface V1RoomFindBookableRsp
 */
export interface V1RoomFindBookableRsp {
    /**
     * 
     * @type {Array<RoomFindBookableRspData>}
     * @memberof V1RoomFindBookableRsp
     */
    data?: Array<RoomFindBookableRspData>;
}


