// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1RoomAdditional } from './v1-room-additional';

/**
 * 
 * @export
 * @interface V1RoomAdditionalList
 */
export interface V1RoomAdditionalList {
    /**
     * 
     * @type {Array<V1RoomAdditional>}
     * @memberof V1RoomAdditionalList
     */
    specialServices?: Array<V1RoomAdditional>;
    /**
     * 
     * @type {number}
     * @memberof V1RoomAdditionalList
     */
    total?: number;
}


