// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1RoomFeatures
 */
export interface V1RoomFeatures {
    /**
     * 评论数量
     * @type {boolean}
     * @memberof V1RoomFeatures
     */
    commentTotal?: boolean | null;
}


