// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 房间基础设施
 * @export
 * @interface V1RoomInfrastructure
 */
export interface V1RoomInfrastructure {
    /**
     * 空调
     * @type {boolean}
     * @memberof V1RoomInfrastructure
     */
    airConditioning?: boolean;
    /**
     * 洗衣机
     * @type {boolean}
     * @memberof V1RoomInfrastructure
     */
    washingMachine?: boolean;
    /**
     * 无线网络
     * @type {boolean}
     * @memberof V1RoomInfrastructure
     */
    wirelessNetwork?: boolean;
    /**
     * 衣架
     * @type {boolean}
     * @memberof V1RoomInfrastructure
     */
    coatHanger?: boolean;
    /**
     * 电视
     * @type {boolean}
     * @memberof V1RoomInfrastructure
     */
    television?: boolean;
    /**
     * 遮光窗帘
     * @type {boolean}
     * @memberof V1RoomInfrastructure
     */
    blackout?: boolean;
}


