// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 房间免费服务
 * @export
 * @interface V1RoomFreeService
 */
export interface V1RoomFreeService {
    /**
     * 早餐
     * @type {boolean}
     * @memberof V1RoomFreeService
     */
    breakfast?: boolean;
    /**
     * 随房管家
     * @type {boolean}
     * @memberof V1RoomFreeService
     */
    housekeeper?: boolean;
    /**
     * 保安服务
     * @type {boolean}
     * @memberof V1RoomFreeService
     */
    securityService?: boolean;
    /**
     * 行李寄存
     * @type {boolean}
     * @memberof V1RoomFreeService
     */
    luggageStorage?: boolean;
    /**
     * 卫生保洁
     * @type {boolean}
     * @memberof V1RoomFreeService
     */
    hygieneCleaning?: boolean;
}


