// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - normal_user: 普通用户  - manager: 系统管理员  - admin: 超级管理员
 * @export
 * @enum {string}
 */
export enum V1RoleName {
    NormalUser = 'normal_user',
    Manager = 'manager',
    Admin = 'admin'
}



