// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 房间收费服务
 * @export
 * @interface V1RoomChargeService
 */
export interface V1RoomChargeService {
    /**
     * 接送机
     * @type {boolean}
     * @memberof V1RoomChargeService
     */
    transfer?: boolean;
    /**
     * SPA服务
     * @type {boolean}
     * @memberof V1RoomChargeService
     */
    spa?: boolean;
    /**
     * 租车服务
     * @type {boolean}
     * @memberof V1RoomChargeService
     */
    carRental?: boolean;
    /**
     * 厨师服务
     * @type {boolean}
     * @memberof V1RoomChargeService
     */
    chefService?: boolean;
    /**
     * 司机服务
     * @type {boolean}
     * @memberof V1RoomChargeService
     */
    driverServices?: boolean;
    /**
     * 儿童看护
     * @type {boolean}
     * @memberof V1RoomChargeService
     */
    childCare?: boolean;
    /**
     * 洗衣服务
     * @type {boolean}
     * @memberof V1RoomChargeService
     */
    laundryService?: boolean;
}


