// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RoomCommentRating } from './room-comment-rating';
import { V1UserInfo } from './v1-user-info';

/**
 * 房间评论
 * @export
 * @interface V1RoomComment
 */
export interface V1RoomComment {
    /**
     * 
     * @type {string}
     * @memberof V1RoomComment
     */
    id: string;
    /**
     * 创建日期
     * @type {string}
     * @memberof V1RoomComment
     */
    createdAt: string;
    /**
     * 修改日期
     * @type {string}
     * @memberof V1RoomComment
     */
    updatedAt: string;
    /**
     * 用户信息
     * @type {V1UserInfo}
     * @memberof V1RoomComment
     */
    userInfo: V1UserInfo;
    /**
     * 评论图片地址
     * @type {Array<string>}
     * @memberof V1RoomComment
     */
    images?: Array<string>;
    /**
     * 评论内容
     * @type {string}
     * @memberof V1RoomComment
     */
    comment: string;
    /**
     * 评级
     * @type {RoomCommentRating}
     * @memberof V1RoomComment
     */
    rating?: RoomCommentRating;
    /**
     * 
     * @type {string}
     * @memberof V1RoomComment
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof V1RoomComment
     */
    roomId: string;
}


