// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Attraction } from './v1-attraction';
import { V1RoomComment } from './v1-room-comment';
import { V1RoomDetail } from './v1-room-detail';

/**
 * 
 * @export
 * @interface V1Room
 */
export interface V1Room {
    /**
     * 
     * @type {string}
     * @memberof V1Room
     */
    id: string;
    /**
     * 创建日期
     * @type {string}
     * @memberof V1Room
     */
    createdAt: string;
    /**
     * 修改日期
     * @type {string}
     * @memberof V1Room
     */
    updatedAt: string;
    /**
     * 房间标题
     * @type {string}
     * @memberof V1Room
     */
    title: string;
    /**
     * 房间所在城市
     * @type {string}
     * @memberof V1Room
     */
    city: string;
    /**
     * 房间所在国家
     * @type {string}
     * @memberof V1Room
     */
    country: string;
    /**
     * 房间分类
     * @type {string}
     * @memberof V1Room
     */
    catalog?: string | null;
    /**
     * 房间详细地址
     * @type {string}
     * @memberof V1Room
     */
    address: string;
    /**
     * 房间原价
     * @type {string}
     * @memberof V1Room
     */
    price: string;
    /**
     * 价格单位
     * @type {string}
     * @memberof V1Room
     */
    unit: string;
    /**
     * 房间评级
     * @type {number}
     * @memberof V1Room
     */
    rating: number;
    /**
     * 房间图片地址
     * @type {Array<string>}
     * @memberof V1Room
     */
    images?: Array<string>;
    /**
     * 房间详情
     * @type {V1RoomDetail}
     * @memberof V1Room
     */
    detail?: V1RoomDetail;
    /**
     * 房间简介
     * @type {string}
     * @memberof V1Room
     */
    description?: string;
    /**
     * 房间经度
     * @type {number}
     * @memberof V1Room
     */
    latitude?: number | null;
    /**
     * 房间纬度
     * @type {number}
     * @memberof V1Room
     */
    longitude?: number | null;
    /**
     * 房间评论
     * @type {Array<V1RoomComment>}
     * @memberof V1Room
     */
    comments?: Array<V1RoomComment>;
    /**
     * 总评论数
     * @type {number}
     * @memberof V1Room
     */
    commentTotal?: number;
    /**
     * 附近景点
     * @type {Array<V1Attraction>}
     * @memberof V1Room
     */
    nearbyAttractions?: Array<V1Attraction>;
}


