// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Room } from './v1-room';

/**
 * 
 * @export
 * @interface V1Rooms
 */
export interface V1Rooms {
    /**
     * 
     * @type {Array<V1Room>}
     * @memberof V1Rooms
     */
    rooms?: Array<V1Room>;
    /**
     * 
     * @type {number}
     * @memberof V1Rooms
     */
    total?: number;
}


