// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1StoryFeatures
 */
export interface V1StoryFeatures {
    /**
     * 喜欢数量, example: true
     * @type {boolean}
     * @memberof V1StoryFeatures
     */
    likeCount?: boolean | null;
    /**
     * 评论数量, example: true
     * @type {boolean}
     * @memberof V1StoryFeatures
     */
    commentCount?: boolean | null;
    /**
     * 喜欢列表, example: true
     * @type {boolean}
     * @memberof V1StoryFeatures
     */
    likeList?: boolean | null;
    /**
     * 评论列表, example: true
     * @type {boolean}
     * @memberof V1StoryFeatures
     */
    commentList?: boolean | null;
}


