// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1UserInfo } from './v1-user-info';

/**
 * 
 * @export
 * @interface V1StoryComment
 */
export interface V1StoryComment {
    /**
     * 
     * @type {string}
     * @memberof V1StoryComment
     */
    id: string;
    /**
     * 创建日期
     * @type {string}
     * @memberof V1StoryComment
     */
    createdAt: string;
    /**
     * 修改日期
     * @type {string}
     * @memberof V1StoryComment
     */
    updatedAt: string;
    /**
     * 用户信息
     * @type {V1UserInfo}
     * @memberof V1StoryComment
     */
    userInfo: V1UserInfo;
    /**
     * 父评论 id
     * @type {string}
     * @memberof V1StoryComment
     */
    parentId?: string | null;
    /**
     * 评论内容
     * @type {string}
     * @memberof V1StoryComment
     */
    Comment: string;
}


