// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - community_kind: 社区种类  - tourism_strategy_kind: 攻略种类
 * @export
 * @enum {string}
 */
export enum V1StoryKind {
    CommunityKind = 'community_kind',
    TourismStrategyKind = 'tourism_strategy_kind'
}



