// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - audit_status: 审核状态  - published: 发布状态
 * @export
 * @enum {string}
 */
export enum V1StoryStatus {
    AuditStatus = 'audit_status',
    Published = 'published'
}



