// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1SpecialOrder } from './v1-special-order';

/**
 * 
 * @export
 * @interface V1SpecialOrders
 */
export interface V1SpecialOrders {
    /**
     * 
     * @type {Array<V1SpecialOrder>}
     * @memberof V1SpecialOrders
     */
    orders?: Array<V1SpecialOrder>;
    /**
     * 
     * @type {number}
     * @memberof V1SpecialOrders
     */
    total?: number;
}


