// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Story } from './v1-story';

/**
 * 
 * @export
 * @interface V1StoryCreateReq
 */
export interface V1StoryCreateReq {
    /**
     * 
     * @type {V1Story}
     * @memberof V1StoryCreateReq
     */
    story: V1Story;
}


