// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Story } from './v1-story';

/**
 * 
 * @export
 * @interface V1StoryFindRsp
 */
export interface V1StoryFindRsp {
    /**
     * 
     * @type {Array<V1Story>}
     * @memberof V1StoryFindRsp
     */
    stories?: Array<V1Story>;
    /**
     * 
     * @type {number}
     * @memberof V1StoryFindRsp
     */
    total?: number;
}


