// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SharingResData } from './sharing-res-data';
import { V1ResKind } from './v1-res-kind';
import { V1UserInfo } from './v1-user-info';

/**
 * 
 * @export
 * @interface V1Sharing
 */
export interface V1Sharing {
    /**
     * 
     * @type {string}
     * @memberof V1Sharing
     */
    id: string;
    /**
     * 分享 id
     * @type {string}
     * @memberof V1Sharing
     */
    shareId: string;
    /**
     * 创建日期
     * @type {string}
     * @memberof V1Sharing
     */
    createdAt: string;
    /**
     * 修改日期
     * @type {string}
     * @memberof V1Sharing
     */
    updatedAt: string;
    /**
     * 用户信息
     * @type {V1UserInfo}
     * @memberof V1Sharing
     */
    userInfo: V1UserInfo;
    /**
     * 分享资源类型
     * @type {V1ResKind}
     * @memberof V1Sharing
     */
    resKind: V1ResKind;
    /**
     * 分享的资源 id
     * @type {number}
     * @memberof V1Sharing
     */
    resId: number;
    /**
     * 分享的资源数据
     * @type {SharingResData}
     * @memberof V1Sharing
     */
    resData: SharingResData;
}


