// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1SpecialServiceDetail
 */
export interface V1SpecialServiceDetail {
    /**
     * 预约方式
     * @type {string}
     * @memberof V1SpecialServiceDetail
     */
    appointmentMethod?: string;
    /**
     * 服务时间
     * @type {string}
     * @memberof V1SpecialServiceDetail
     */
    serviceTime?: string;
    /**
     * 使用规则
     * @type {string}
     * @memberof V1SpecialServiceDetail
     */
    usageRules?: string;
}


