// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1StoryOperationType } from './v1-story-operation-type';
import { V1UserInfo } from './v1-user-info';

/**
 * 
 * @export
 * @interface V1StoryOperation
 */
export interface V1StoryOperation {
    /**
     * 
     * @type {string}
     * @memberof V1StoryOperation
     */
    id: string;
    /**
     * 操作类型
     * @type {V1StoryOperationType}
     * @memberof V1StoryOperation
     */
    operation: V1StoryOperationType;
    /**
     * 用户信息
     * @type {V1UserInfo}
     * @memberof V1StoryOperation
     */
    userInfo: V1UserInfo;
}


