// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1StoryComment } from './v1-story-comment';
import { V1StoryKind } from './v1-story-kind';
import { V1StoryOperation } from './v1-story-operation';
import { V1StoryStatus } from './v1-story-status';
import { V1UserInfo } from './v1-user-info';

/**
 * 
 * @export
 * @interface V1Story
 */
export interface V1Story {
    /**
     * 
     * @type {string}
     * @memberof V1Story
     */
    id: string;
    /**
     * 文章内容, 富文本内容
     * @type {string}
     * @memberof V1Story
     */
    article: string;
    /**
     * 图片列表地址
     * @type {Array<string>}
     * @memberof V1Story
     */
    images: Array<string>;
    /**
     * 涉及到的酒店房间
     * @type {Array<string>}
     * @memberof V1Story
     */
    rooms?: Array<string>;
    /**
     * 用户信息
     * @type {V1UserInfo}
     * @memberof V1Story
     */
    userInfo: V1UserInfo;
    /**
     * 文章类型
     * @type {V1StoryKind}
     * @memberof V1Story
     */
    kind: V1StoryKind;
    /**
     * 
     * @type {V1StoryStatus}
     * @memberof V1Story
     */
    status: V1StoryStatus;
    /**
     * 喜欢数量
     * @type {number}
     * @memberof V1Story
     */
    likeCount?: number | null;
    /**
     * 评论数量
     * @type {number}
     * @memberof V1Story
     */
    commentCount?: number | null;
    /**
     * 喜欢列表
     * @type {Array<V1StoryOperation>}
     * @memberof V1Story
     */
    operations?: Array<V1StoryOperation>;
    /**
     * 评论列表
     * @type {Array<V1StoryComment>}
     * @memberof V1Story
     */
    comments?: Array<V1StoryComment>;
}


