// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1SpecialOrderDetail
 */
export interface V1SpecialOrderDetail {
    /**
     * 订单取消原因
     * @type {string}
     * @memberof V1SpecialOrderDetail
     */
    cancelReason?: string;
    /**
     * 客户姓名
     * @type {string}
     * @memberof V1SpecialOrderDetail
     */
    customerName: string;
    /**
     * 客户电话
     * @type {string}
     * @memberof V1SpecialOrderDetail
     */
    customerPhone: string;
}


