// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1SearchPopularCitiesRspCity } from './v1-search-popular-cities-rsp-city';

/**
 * 
 * @export
 * @interface V1SearchPopularCitiesRsp
 */
export interface V1SearchPopularCitiesRsp {
    /**
     * 城市数据列表
     * @type {Array<V1SearchPopularCitiesRspCity>}
     * @memberof V1SearchPopularCitiesRsp
     */
    cities?: Array<V1SearchPopularCitiesRspCity>;
    /**
     * 
     * @type {number}
     * @memberof V1SearchPopularCitiesRsp
     */
    total?: number;
}


