// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1SpecialService } from './v1-special-service';

/**
 * 
 * @export
 * @interface V1SpecialServices
 */
export interface V1SpecialServices {
    /**
     * 
     * @type {Array<V1SpecialService>}
     * @memberof V1SpecialServices
     */
    specialServices?: Array<V1SpecialService>;
    /**
     * 
     * @type {number}
     * @memberof V1SpecialServices
     */
    total?: number;
}


