// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Sharing } from './v1-sharing';

/**
 * 
 * @export
 * @interface V1SharingList
 */
export interface V1SharingList {
    /**
     * 
     * @type {Array<V1Sharing>}
     * @memberof V1SharingList
     */
    shares?: Array<V1Sharing>;
    /**
     * 
     * @type {number}
     * @memberof V1SharingList
     */
    total?: number;
}


