// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Task } from './v1-task';

/**
 * 
 * @export
 * @interface V1TaskCreateReq
 */
export interface V1TaskCreateReq {
    /**
     * 
     * @type {V1Task}
     * @memberof V1TaskCreateReq
     */
    task?: V1Task;
}


