// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1Task } from './v1-task';

/**
 * 
 * @export
 * @interface V1Tasks
 */
export interface V1Tasks {
    /**
     * 
     * @type {Array<V1Task>}
     * @memberof V1Tasks
     */
    data?: Array<V1Task>;
    /**
     * 
     * @type {number}
     * @memberof V1Tasks
     */
    total?: number;
}


