// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TaskStatus 任务状态，- Created: task create initial state  - Running: Work is in progress
 * @export
 * @enum {string}
 */
export enum V1TaskStatus {
    Created = 'Created',
    Running = 'Running',
    Success = 'Success',
    Failed = 'Failed',
    Canceled = 'Canceled'
}



