// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1UserFindReq
 */
export interface V1UserFindReq {
    /**
     * 
     * @type {string}
     * @memberof V1UserFindReq
     */
    sortBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof V1UserFindReq
     */
    page?: number | null;
    /**
     * 
     * @type {number}
     * @memberof V1UserFindReq
     */
    pageSize?: number | null;
}


