// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 获取用户信息请求
 * @export
 * @interface V1UserDetailReq
 */
export interface V1UserDetailReq {
    /**
     * 
     * @type {string}
     * @memberof V1UserDetailReq
     */
    id: string;
}


