// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { V1User } from './v1-user';

/**
 * 
 * @export
 * @interface V1Users
 */
export interface V1Users {
    /**
     * 
     * @type {Array<V1User>}
     * @memberof V1Users
     */
    users?: Array<V1User>;
    /**
     * 
     * @type {number}
     * @memberof V1Users
     */
    total?: number;
}


