// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface V1kitchenFacilities
 */
export interface V1kitchenFacilities {
    /**
     * 冰箱
     * @type {boolean}
     * @memberof V1kitchenFacilities
     */
    refrigerator?: boolean;
    /**
     * 热水壶
     * @type {boolean}
     * @memberof V1kitchenFacilities
     */
    kettle?: boolean;
    /**
     * 炉灶
     * @type {boolean}
     * @memberof V1kitchenFacilities
     */
    kitchenRange?: boolean;
    /**
     * 微波炉
     * @type {boolean}
     * @memberof V1kitchenFacilities
     */
    microwaveOven?: boolean;
}


