// tslint:disable
/**
 * openapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * - English: 英语  - Japanese: 日语  - Thai: 泰语  - Burmese: 缅甸语  - Chinese: 中文
 * @export
 * @enum {string}
 */
export enum V1language {
    English = 'English',
    Japanese = 'Japanese',
    Thai = 'Thai',
    Burmese = 'Burmese',
    Chinese = 'Chinese'
}



